app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('app1_fir/',app1_fir,name='app1_fir'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('app2_sec/',app2_sec,name='app2_sec'),
]

django9/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
from app1.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app_string/',app_string,name='app_string'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def app1_fir(request):
    return render(request,'app1_first.html')


def app_string(request):
    return HttpResponse('<h1>hi this is string response</h1>')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_sec(request):
    return render(request,'app2_second.html')

templates/app1_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is app1 html page response</h1>
    <h2>navigation links</h2>

    <h6><a href="{% url 'app2:app2_sec' %}">go to app2 html page</a></h6>

    <h6><a href="{% url 'app_string' %}">go to app string response</a></h6>
</body>
</html>

templates/app2_second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is app2 html page response</h1>
    <h2>navigation links</h2>

    <h6><a href="{% url 'app1:app1_fir' %}">go to app1 html page</a></h6>

    <h6><a href="{% url 'app_string' %}">go to app string response</a></h6>
</body>
</html>